services: 
  php:
    image: php:8-fpm
    container_name: ${APP_NAME}-php
    volumes:
      - ../.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ..:/var/www/html
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    volumes:
      - ../.docker/nginx/default.conf:/tmp/default.template
      - ../.docker/certs:/etc/certs
      - ..:/var/www/html
    depends_on:
      - php
    restart: unless-stopped
    entrypoint: /bin/bash -c 'cat /tmp/default.template | sed "s/\\\$$domain/${DOMAIN}/g" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'

  node:
    image: node:22-alpine
    container_name: ${APP_NAME}-node
    working_dir: /var/www/html
    volumes:
      - ..:/var/www/html
      - node_modules:/var/www/html/node_modules
    command: sh -c "npm ci --no-audit --no-fund --no-update-notifier --loglevel=error && exec node builder.js --watch"
    restart: unless-stopped

volumes:
  node_modules:
